### ISSUE TITLE
Forget Watch on Watches screen does nothing

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#103]
Button should presumably delete the watch from menu?

**Comment by AliceGrey** [comment]
@matejdro currently it should unregister the device from pairedStorage but that currently seems to fail on the current Master.

```
E/flutter (21049): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'WhereIterable<StoredDevice>' is not a subtype of type 'List<StoredDevice>'
E/flutter (21049): #0      PairedStorage.unregister (package:cobble/infrastructure/datasources/paired_storage.dart:68:5)
E/flutter (21049): #1      MyWatchesTab.build._onForgetPressed (package:cobble/ui/home/tabs/watches_tab.dart:110:21)
E/flutter (21049): #2      MyWatchesTab.build._onSettingsPressed.<anonymous closure>.<anonymous closure> (package:cobble/ui/home/tabs/watches_tab.dart:208:50)
E/flutter (21049): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (21049): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (21049): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (21049): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (21049): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (21049): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (21049): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (21049): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (21049): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (21049): #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (21049): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (21049): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (21049): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (21049): #16     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (21049): #17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21049): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (21049): #19     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (21049): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (21049): 
```
