### ISSUE TITLE
BLE: Random disconnects, especially annoying on Android 10

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#131]
It seems like watch will disconnect at random times from BLE.

This is especially annoying on Android 10 where it does not reconnect back properly.

I will get logs ASAP, just wanted to log that issue first.

(this is happening with both `ble_cleanup` branch and normal branch).

**Comment by matejdro** [comment]
Logs of one such instance:

```
E 14:54:46.560 [ProtocolIOZ] Read loop returning
D 14:54:46.564 [BlueLEDriver$startSingleWatchConnection$1$1$sendLoopZ] Packet sending loop exited
D 14:54:46.564 [BlueLEDriverZ] Driver shutting down
D 14:54:46.567 [BlueGATTServerZ] Server closing connection
D 14:54:46.593 [BlueLEDriverZ] Driver shutting down
D 14:54:46.594 [BlueGATTServerZ] Server closing connection
E 14:54:46.598 [ConnectionLooper$connectToWatchZ] Watch connection error
java.io.IOException: Pipe broken
	at java.io.PipedInputStream.read(PipedInputStream.java:326)
	at java.io.PipedInputStream.read(PipedInputStream.java:384)
	at io.rebble.cobble.bluetooth.InputStreamExtensionKt$readFully$2.invokeSuspend(inputStreamExtension.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

java.io.IOException: Pipe broken
	at java.io.PipedInputStream.read(PipedInputStream.java:326)
	at java.io.PipedInputStream.read(PipedInputStream.java:384)
	at io.rebble.cobble.bluetooth.InputStreamExtensionKt$readFully$2.invokeSuspend(inputStreamExtension.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
D 14:54:46.599 [ConnectionLooper$connectToWatchZ] Watch connection failed, waiting and reconnecting after 4000 ms
D 14:54:46.602 [ServiceLifecycleControl$1$invokeSuspend$$inlined$collectZ] Watch connection status io.rebble.cobble.bluetooth.ConnectionState$WaitingForReconnect@23a0419
D 14:54:46.614 [WatchService$startNotificationLoop$1$invokeSuspend$$inlined$collectZ] Update notification state io.rebble.cobble.bluetooth.ConnectionState$WaitingForReconnect@23a0419
```
