### ISSUE TITLE
Device calendar errors leading to calendar events not appearing on the watch

### ISSUE THREAD

**Issue by hellcp** [pebble-dev/mobile-app#240]
I keep seeing the following error, which seems to be the reason behind calendar not being synced to the watch:
```
D/Cobble  (23680): [CalendarHandler$startCalendarHandler] Watch service started or we received permissions. Syncing calendar...
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): Failed to handle method call
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): kotlin.UninitializedPropertyAccessException: lateinit property _calendarDelegate has not been initialized
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at com.builttoroam.devicecalendar.DeviceCalendarPlugin.onMethodCall(DeviceCalendarPlugin.kt:118)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at android.app.ActivityThread.main(ActivityThread.java:8194)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#plugins.builttoroam.com/device_calendar(23680): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/flutter (23680): PlatformException(error, lateinit property _calendarDelegate has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property _calendarDelegate has not been initialized
I/flutter (23680): 	at com.builttoroam.devicecalendar.DeviceCalendarPlugin.onMethodCall(DeviceCalendarPlugin.kt:118)
I/flutter (23680): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (23680): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
I/flutter (23680): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
I/flutter (23680): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
I/flutter (23680): 	at android.os.Handler.handleCallback(Handler.java:958)
I/flutter (23680): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (23680): 	at android.os.Looper.loopOnce(Looper.java:205)
I/flutter (23680): 	at android.os.Looper.loop(Looper.java:294)
I/flutter (23680): 	at android.app.ActivityThread.main(ActivityThread.java:8194)
I/flutter (23680): 	at java.lang.reflect.Method.invoke
D/Cobble  (23680): [CalendarHandler$startCalendarHandler] Sync complete
```

**Comment by hellcp** [comment]
Seems like it's related to https://github.com/builttoroam/device_calendar/pull/431

**Comment by hellcp** [comment]
This is resolved on rws branch now
